const mongoose = require('mongoose');

const generatedPatientReportSchema = new mongoose.Schema({
    patientId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Patient',
        required: [true, 'Patient ID is required']
    },
    generatedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: [true, 'Generated by user is required']
    },
    reportType: {
        type: String,
        required: [true, 'Report type is required'],
        enum: ['comprehensive', 'screening-summary', 'risk-assessment', 'referral-history', 'care-plan-summary', 'follow-up-summary']
    },
    dateRange: {
        startDate: { type: Date, required: true },
        endDate: { type: Date, required: true }
    },
    includeSections: {
        demographics: { type: Boolean, default: true },
        screeningHistory: { type: Boolean, default: true },
        riskScores: { type: Boolean, default: true },
        referrals: { type: Boolean, default: true },
        carePlans: { type: Boolean, default: true },
        followUps: { type: Boolean, default: true },
        notes: { type: Boolean, default: false }
    },
    reportData: { type: mongoose.Schema.Types.Mixed },
    format: { type: String, enum: ['json', 'summary'], default: 'json' },
    isActive: { type: Boolean, default: true }
}, { timestamps: true });

generatedPatientReportSchema.index({ patientId: 1, createdAt: -1 });
generatedPatientReportSchema.index({ generatedBy: 1 });
generatedPatientReportSchema.index({ reportType: 1 });

module.exports = mongoose.model('GeneratedPatientReport', generatedPatientReportSchema);
